### ISSUE TITLE
Please don't directly edit playerdata

### ISSUE THREAD

**Issue by SFGrenade** [YoJames2019/PersistentDivine#1]
https://github.com/YoJames2019/PersistentDivine/blob/d0f6074b2eea8da704932830dc42064c4be7b53d/PersistentDivine/PersistentDivine.cs#L46-L51

maybe converting those to ModHooks.GetPlayerBoolHook hooks would be better as the playerdata itself wouldn't be edited.

**Comment by YoJames2019** [comment]
I apologize, I'm new to this whole modding hk thing, could you explain further?

Would this be better?

```csharp           
if ((pd.GetBool("legEaterLeft") && pd.GetBool("defeatedNightmareGrimm") && pd.GetBool("divineFinalConvo") && !(scf.name == "Grimm_Divine" && sct.name == "Town")) || !pd.GetBool("nightmareLanternLit"))
{
    Log("Divine is nowhere to be found");
    pd.SetBool("divineInTown", false);
}
else
{
    Log("The lantern was lit, and the Divine quest not complete, Divine will stay");
    pd.SetBool("divineInTown", true);
}
```

**Comment by SFGrenade** [comment]
In `Initialize`, add:
```cs
ModHooks.GetPlayerBoolHook += OnGetPlayerBoolHook;
```
then, below `Initialize`, add:
```cs
private bool OnGetPlayerBoolHook(string target, bool orig)
{
    if (target == "divineInTown")
    {
        return !((pd.GetBool("legEaterLeft") && pd.GetBool("defeatedNightmareGrimm") && pd.GetBool("divineFinalConvo")) || !pd.GetBool("nightmareLanternLit"));
    }
    return orig;
}
```

this should be the same as your code, but won't make changes to playerdata

**Comment by YoJames2019** [comment]
Ahhhh ok I didn’t understand what you meant because I didn’t fully understand how ModHooks worked, that clears it up for me, thank you so much

**Comment by YoJames2019** [comment]
I’ll implement it when I get back to my pc
